### PR TITLE
Normalize line endings

### PR DESCRIPTION
**Pull request by enricosada**
i am trying to use this repo as subtree for visualfsharp ( but it's the same problem cloning the repo ), because if i add a gitattributes, all file endings need to be normalized. 
This is annoing if i try to merge/pull later.

i used the [PTVS .gitattributes file](https://github.com/Microsoft/PTVS/blob/7d9a06dc9d01d07d4b0587d471222854360d40f1/.gitattributes). 
It's pretty much the same work done by PTVS in Microsoft/PTVS@0dc3aa73b4522ed283e4e432beb21d4ab966a962

I used the procedure https://help.github.com/articles/dealing-with-line-endings/ 

if you want to repro the problem:

1. `mkdir repo && cd repo`
1. `git init` 
1. `echo * text=auto >.gitattributes`
1. `git add . && git commit -am "add .gitattributes"` 
1. `git subtree add --prefix Common https://github.com/Microsoft/VisualStudio-SharedProject.git master --squash` 
1. `git rm --cached -r . && git reset --hard` 

subtree ok, but all files need to fix the line endings ( `git status` )

if you use this pr, works (use `git subtree add --prefix Common https://github.com/enricosada/VisualStudio-SharedProject.git normalize_line_endings --squash` )

### CODE REVIEW

**Comment by enricosada** [comment]
i see nodejstool doesnt do `text=auto` in .gitatttributes, @mousetraps it's a problem to normalize this repo?

**Comment by zooba** [comment]
Ping @mousetraps - I'm okay with this change, so unless you've got any concerns you can go ahead and merge it.

**Comment by mousetraps** [comment]
:+1: and sorry for the delay. There is a *reason*, but no particularly *good* reason we haven't normalized in NTVS.

**Comment by enricosada** [comment]
thx @mousetraps and @zooba , it's easier to send contribution back from Microsoft/visualfsharp with normalized encoding, because without was going to be really annoying with merge.

Let's integrate it in visualfsharp now :smile:

**Pull request merged**
